[buildPlans.iosevka-mk]
family = "Iosevka"
design = [
  "sans",
  "sp-fixed",
  "v-capital-g-toothless",
  "v-zero-slashed",
  "v-one-nobase",
  "v-tilde-low",
  "v-asterisk-hexlow",
  "v-caret-high",
  "v-underscore-low",
  "v-at-short",
  "v-numbersign-upright",
  "v-dollar-through",
  "v-percent-rings",
]

# Only normal, no extended.
[buildPlans.iosevka-mk.widths.normal]
shape = 5
menu = 5
css = "normal"

# Only normal and italic, no oblique.
[buildPlans.iosevka-mk.slants]
upright = "normal"
italic = "italic"
