[buildPlans.iosevka-mk]
family = "Iosevka"
design = [
  "sans",
  "sp-fixed",
  "ss20",
  "v-capital-g-toothless",
  "v-zero-slashed",
  "v-one-nobase",
  "v-tilde-low",
  "v-asterisk-low",
  "v-caret-high",
  "v-underscore-low",
  "v-at-short",
  "v-numbersign-upright",
  "v-dollar-through",
  "v-percent-rings",
]

# Build normal, and also extended for BQN.
[buildPlans.iosevka-mk.widths.normal]
shape = 500
menu = 5
css = "normal"
[buildPlans.iosevka-mk.widths.extended]
shape = 600
menu = 7
css = "expanded"

# Only build normal and italic, not oblique.
[buildPlans.iosevka-mk.slopes.upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"
[buildPlans.iosevka-mk.slopes.italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"
